### ISSUE TITLE
Setting default language on startup is not working

### ISSUE THREAD

**Issue by ahmetsekmen** [SyncfusionExamples/blazor-localization#1]
Hi,
thanks for project.
In server side project
I am setting default language to "de" in start up but its not working;

options.DefaultRequestCulture = new RequestCulture("de");

![image](https://user-images.githubusercontent.com/10855574/87031465-dac46200-c1eb-11ea-8ae9-40951b974809.png)

**Comment by syncsiva** [comment]
Refer below links to set culture on start up
https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-6.0&pivots=server#statically-set-the-culture
https://docs.microsoft.com/en-us/aspnet/core/blazor/globalization-localization?view=aspnetcore-6.0&pivots=webassembly#statically-set-the-culture
